<template>
    <div class="brave">
     <div class="section">
         <h1>{{ title }}</h1>
         <span><p>{{ sub_title }}</p></span>
     </div>
     <div class="brave-one">
        <span><svg @click="toogleContentOne" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
   <path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75l3 3m0 0l3-3m-3 3v-7.5M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
 </svg></span>
 
         <h3>{{ one }}</h3>
 
         <p v-if="showContentOne">{{ sub_one }}</p>
         <hr>
 
 
     
         <svg @click="toogleContentTwo" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
   <path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75l3 3m0 0l3-3m-3 3v-7.5M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
 </svg>
 
 <!-- <svg  xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
   <path stroke-linecap="round" stroke-linejoin="round" d="M15 11.25l-3-3m0 0l-3 3m3-3v7.5M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
 </svg> -->
 
          <h3>{{ two }}</h3>
        
         <p v-if="showContentTwo">{{ sub_two }}</p> 
         <hr>
 
         <svg @click="toogleContentThree" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
   <path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75l3 3m0 0l3-3m-3 3v-7.5M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
 </svg>
         <h3>{{ three }}</h3>
 
         <p v-if="showContentThree">{{ sub_three }}</p>
         <hr>
 
         <svg @click="toogleContentFour" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
   <path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75l3 3m0 0l3-3m-3 3v-7.5M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
 </svg>
         <h3>{{ four }}</h3>
       
 
         <p v-if="showContentFour">{{ sub_four }}</p>
         <hr>
 
         <svg @click="toogleContentFive" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
   <path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75l3 3m0 0l3-3m-3 3v-7.5M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
 </svg>
         <h3>{{ five }}</h3>
        
 
         <p v-if="showContentFive">{{ sub_five }}</p>
         <hr>
 
         <svg @click="toogleContentSix" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
   <path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75l3 3m0 0l3-3m-3 3v-7.5M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
 </svg>
         <h3>{{ six }}</h3>
        
         <span><p v-if="showContentSix">{{ sub_six }}</p></span>
         <hr>
     </div>
     
    </div>
 </template>
 <script>
   export default{
     data(){
         return{
             showContentOne:false,
             showContentTwo:false,
             showContentThree:false,
             showContentFour:false,
             showContentFive:false,
             showContentSix:false,
           
             title:'FAQ',
             sub_title:'Frequently asked questions',
             one:'What is a URL shortener?',
             sub_one:'A Url shortener is a tool that converts long and complex URLs into shorter, more manageable links. It makes sharing links easier and can also provide tracking and analytics features.',
             two:'How do i use your URL shortener?',
             sub_two:'A Url shortener is a tool that converts long and complex URLs into shorter, more manageable links. It makes sharing links easier and can also provide tracking and analytics features.',
             three:'Can i customise my short links?',
             sub_three:'A Url shortener is a tool that converts long and complex URLs into shorter, more manageable links. It makes sharing links easier and can also provide tracking and analytics features.',
             four:'Are there analytics available for my short links?',
             sub_four:'A Url shortener is a tool that converts long and complex URLs into shorter, more manageable links. It makes sharing links easier and can also provide tracking and analytics features.',
             five:'Is there a limit to the number of links i can shorten?',
             sub_five:'A Url shortener is a tool that converts long and complex URLs into shorter, more manageable links. It makes sharing links easier and can also provide tracking and analytics features.',
             six:'How long are the short links generated by your platform?',
             sub_six:'A Url shortener is a tool that converts long and complex URLs into shorter, more manageable links. It makes sharing links easier and can also provide tracking and analytics features.',
             
         }
     },
     methods:{
         toogleContentOne(){
             this.showContentOne = !this.showContentOne;
         },
         toogleContentTwo(){
             this.showContentTwo = !this.showContentTwo;
         },
         toogleContentThree(){
             this.showContentThree = !this.showContentThree;
         },
         toogleContentFour(){
             this.showContentFour = !this.showContentFour;
         },
         toogleContentFive(){
             this.showContentFive = !this.showContentFive;
         },
         toogleContentSix(){
             this.showContentSix = !this.showContentSix;
         },
     }
   }
 </script>
 
 <style >
     .brave{
         background-color:  rgb(182, 182, 192);
         padding-top:70px;
     }
     .section{
         text-align: center;
         margin-top:40px;
        
     }
     .section  span p{
         margin-top:30px;
         color: rgb(32, 32, 184);
         text-align:center;
         font-weight:bolder;
         margin-bottom:90px;
     }
     .brave-one h3{
         margin-left:50px;
         color:rgb(32, 32, 184);
         margin-top:30px;
     }
 
     .brave-one svg{
         position:absolute;
         width:30px; 
          height:30px;
         left:75%;
         /* padding-bottom:20px; */
         padding-bottom:-40px;
         /* bottom:-150%; */
         cursor:pointer;
         color:rgb(32, 32, 184);
         margin-top:20px;
         /* margin-bottom:10px; */
        
     }
     .brave-one span svg{
         /* position:absolute; */
         width:30px;
         height:30px;
         left:75%;
         padding-bottom:40px;
         cursor:pointer;
         color:rgb(32, 32, 184);
         /* margin-top:20px; */
         bottom:-156%;  
        
     }
     .brave-one p{
         margin-left:50px;
         margin-top:40px;
         margin-bottom:40px;
         border-bottom-style:underline;
     }
   .brave-one span p{
         margin-left:50px;
         margin-top:40px;
         padding-bottom:60px;
   }

   /* @media (max-width: 767px) {  */
  /* Your CSS for mobile phones (portrait) here */

   /* .brave-one h3{
        margin-left:50px;
        color:rgb(32, 32, 184);
        margin-top:30px;
        font-size:small;
        margin-left:10px;
    }

    .brave-one svg{
        position:absolute;
        width:15px; 
         height:15px;
        left:78%;  */
/*       
     }
    .brave-one span svg{
        position:absolute;
        width:15px;
        height:15px;
        left:15%;
        padding-bottom:40px;
        cursor:pointer;
        color:rgb(32, 32, 184);  */
       
         /* bottom:-340%;
    }
}  */


 </style>
 
   